---
- name: Add K8S Token and Hash to dummy host
  add_host:
    name: K8S_NODE_HOLDER
    node_server:  '{{ inventory_hostname }}'
    node_addr: '{{ ansible_default_ipv4.address }}'
  tags:
    - node_join
    - install