- name: Add K8S Token and Hash to dummy host
  add_host:
    name:   "K8S_MASTER_HOLDER"
    master_server:  "{{ inventory_hostname }}"
    api_addr: "{{ ansible_default_ipv4.address }}"
  when:
    - master is defined
  tags:
    - node_join
    - install
    - test

